language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: ududnvDftfylIiSRCe3EpXubvKajMTjCyZtf7n2+UaqAyO7ox/uLMgpY3n8xZcbhR4Kum/+804rKq1u3kg1ULqEMDT5T2otPW30CMeZbSNKm9SapAIN8P8hEQy2YQBh46UK/7Vmdvk5Nd1Yh0YiyC9HOjOt5FB5TnW+r3u/+pwn7l3XjkTcAmhL3jeciXMgUXgp4IWoiNj+VHDukqH4Cq3r29meXIirU1EK5a8Lo2g6tW6CvzjXmz2269q2oWFfKp/FKmuGJKSE8CS7rWNzrOXoBGiXmopKa3SdYgKrMxJIPcTQpC7Hw+d7y9UpkcHNRe9mGAloFoZQ/QcZQM1OyHBZY/camqvj7fuI9Xg3JOHKxVSIGK+7cGi6DVJzOtlA/IV+zV71gab385p5+KNuW8Cb3HHqc1xyPhiJR/p+sLbGs6Hq0a9YnzN6B/cp17stpNDGEHd2VMsiDUw4TCRk7LJVpPGqdBqKIWgyK0kQN/t8sBLSDxvhyKRPbSkGZg03uJgZ5Rp0Vgpb5YoFjtss0ryklVrHl7bgyz9SOSiSkRJeVGSHi7HccyVaIarcmRpdWzU8C3MNZpUfloESdq0C7wVhJ6GcWOJwiT4WrPLgZ9ppB0oKZMJ8tW6hbWIovhwjofffS+mKRlsMYY8UOUdXQBhiDy6AVQaXhs54NUDNT3Vg=
  app: the-backend
